# Generated by Django 5.0.6 on 2025-10-17 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0036_assignment_unique_assignment_20240320_1310"),
        ("submissions", "0009_submission_index"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_step", models.PositiveIntegerField(default=1)),
                (
                    "step_completions",
                    models.JSONField(
                        default=dict,
                        help_text="Tracks completed operations per step: {step: [operation_type, ...]}",
                    ),
                ),
                (
                    "activity_logs",
                    models.JSONField(
                        default=list,
                        help_text="Array of timestamped events: [{timestamp, step, operation, data}, ...]",
                    ),
                ),
                (
                    "question_responses",
                    models.JSONField(
                        default=dict,
                        help_text="Student responses to embedded questions: {question_id: response, ...}",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assignment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_progress",
                        to="assignments.assignment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity Progress",
                "verbose_name_plural": "Activity Progress",
            },
        ),
    ]
