# Generated by Django 5.0.6 on 2025-10-17 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0011_add_participant_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="activityprogress",
            name="audio_edit_history",
            field=models.JSONField(
                default=list,
                help_text="Array of edit history states for undo/redo: [{url, effectName, metadata}, ...]",
            ),
        ),
        migrations.AddField(
            model_name="activityprogress",
            name="audio_metadata",
            field=models.JSONField(
                default=dict,
                help_text="Additional audio metadata: {duration, sampleRate, numberOfChannels, ...}",
            ),
        ),
        migrations.AddField(
            model_name="activityprogress",
            name="current_audio_url",
            field=models.TextField(
                blank=True, help_text="Current audio blob URL or file path", null=True
            ),
        ),
    ]
