# Generated by Django 5.0.6 on 2024-10-27 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instruments", "0004_instrument_midi_program_number"),
        (
            "musics",
            "0027_correct_accompaniment_2040_and_deep_river_color_pattern_20240317_1712",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PartInstrumentSample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sample_audio", models.FileField(upload_to="instrument_samples/")),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="instruments.instrument",
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="instrument_samples",
                        to="musics.part",
                    ),
                ),
            ],
            options={
                "verbose_name": "Part Instrument Sample",
                "verbose_name_plural": "Part Instrument Samples",
                "unique_together": {("part", "instrument")},
            },
        ),
    ]
