#!/usr/bin/env bash
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_GVrg4i0.mp3 ~/Downloads/student-recoding_GVrg4i0.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_o2nOi8z.mp3 ~/Downloads/student-recoding_o2nOi8z.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_Kz3PK8b.mp3 ~/Downloads/student-recoding_Kz3PK8b.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_Ct3HOAB.mp3 ~/Downloads/student-recoding_Ct3HOAB.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_q9RoQUL.mp3 ~/Downloads/student-recoding_q9RoQUL.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_nNQqAQa.mp3 ~/Downloads/student-recoding_nNQqAQa.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_zvUrV9s.mp3 ~/Downloads/student-recoding_zvUrV9s.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_dfsFDCe.mp3 ~/Downloads/student-recoding_dfsFDCe.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_cJGiiHg.mp3 ~/Downloads/student-recoding_cJGiiHg.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_2Ab7E6k.mp3 ~/Downloads/student-recoding_2Ab7E6k.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_Fz95M8L.mp3 ~/Downloads/student-recoding_Fz95M8L.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_vvA8WCn.mp3 ~/Downloads/student-recoding_vvA8WCn.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_hlbzOyn.mp3 ~/Downloads/student-recoding_hlbzOyn.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_mDXD055.mp3 ~/Downloads/student-recoding_mDXD055.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_q3OLTYX.mp3 ~/Downloads/student-recoding_q3OLTYX.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_9yTfTDc.mp3 ~/Downloads/student-recoding_9yTfTDc.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_Vrff3AR.mp3 ~/Downloads/student-recoding_Vrff3AR.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_IvWwZvs.mp3 ~/Downloads/student-recoding_IvWwZvs.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_ECQbzdc.mp3 ~/Downloads/student-recoding_ECQbzdc.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_mgbTZQ5.mp3 ~/Downloads/student-recoding_mgbTZQ5.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_o0w7I2i.mp3 ~/Downloads/student-recoding_o0w7I2i.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_9q41nUa.mp3 ~/Downloads/student-recoding_9q41nUa.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_nigns91.mp3 ~/Downloads/student-recoding_nigns91.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_YgXCjdw.mp3 ~/Downloads/student-recoding_YgXCjdw.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_NSmKGLZ.mp3 ~/Downloads/student-recoding_NSmKGLZ.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_yuhY7RQ.mp3 ~/Downloads/student-recoding_yuhY7RQ.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_WwrWR2Y.mp3 ~/Downloads/student-recoding_WwrWR2Y.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_H89ZppX.mp3 ~/Downloads/student-recoding_H89ZppX.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_7HSdu1W.mp3 ~/Downloads/student-recoding_7HSdu1W.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_MZq7QYX.mp3 ~/Downloads/student-recoding_MZq7QYX.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_bZ6aNDw.mp3 ~/Downloads/student-recoding_bZ6aNDw.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_DS9IoTu.mp3 ~/Downloads/student-recoding_DS9IoTu.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_xIsxoWJ.mp3 ~/Downloads/student-recoding_xIsxoWJ.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_PIf0F0r.mp3 ~/Downloads/student-recoding_PIf0F0r.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_LQGEL2k.mp3 ~/Downloads/student-recoding_LQGEL2k.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_4ffAmpC.mp3 ~/Downloads/student-recoding_4ffAmpC.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_ITtSUdT.mp3 ~/Downloads/student-recoding_ITtSUdT.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_kbRTQ47.mp3 ~/Downloads/student-recoding_kbRTQ47.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_lI7nTGV.mp3 ~/Downloads/student-recoding_lI7nTGV.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_lYMRvRv.mp3 ~/Downloads/student-recoding_lYMRvRv.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_jrERcL3.mp3 ~/Downloads/student-recoding_jrERcL3.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_iN0VnCG.mp3 ~/Downloads/student-recoding_iN0VnCG.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_G3vcexh.mp3 ~/Downloads/student-recoding_G3vcexh.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_YhaE8he.mp3 ~/Downloads/student-recoding_YhaE8he.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_clPknnv.mp3 ~/Downloads/student-recoding_clPknnv.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_rOsNeQh.mp3 ~/Downloads/student-recoding_rOsNeQh.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_iuP2KFm.mp3 ~/Downloads/student-recoding_iuP2KFm.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_HnHWseg.mp3 ~/Downloads/student-recoding_HnHWseg.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_7Hvqcr4.mp3 ~/Downloads/student-recoding_7Hvqcr4.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_1U8tj1W.mp3 ~/Downloads/student-recoding_1U8tj1W.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_PFTRGdO.mp3 ~/Downloads/student-recoding_PFTRGdO.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_dMWpv4i.mp3 ~/Downloads/student-recoding_dMWpv4i.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_2JKULZF.mp3 ~/Downloads/student-recoding_2JKULZF.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_9wxiZK2.mp3 ~/Downloads/student-recoding_9wxiZK2.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_zTEMI37.mp3 ~/Downloads/student-recoding_zTEMI37.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_VDyqi0o.mp3 ~/Downloads/student-recoding_VDyqi0o.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_fcNTpJk.mp3 ~/Downloads/student-recoding_fcNTpJk.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_EyXlNlC.mp3 ~/Downloads/student-recoding_EyXlNlC.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_QnV0mmy.mp3 ~/Downloads/student-recoding_QnV0mmy.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_LF1RBsb.mp3 ~/Downloads/student-recoding_LF1RBsb.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_4jGriN2.mp3 ~/Downloads/student-recoding_4jGriN2.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_J9u3lpz.mp3 ~/Downloads/student-recoding_J9u3lpz.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_mbj5oXd.mp3 ~/Downloads/student-recoding_mbj5oXd.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_RToNE09.mp3 ~/Downloads/student-recoding_RToNE09.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_NFUbi0Z.mp3 ~/Downloads/student-recoding_NFUbi0Z.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_BGy4Yx4.mp3 ~/Downloads/student-recoding_BGy4Yx4.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_NY8A3aJ.mp3 ~/Downloads/student-recoding_NY8A3aJ.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_8kzmRlv.mp3 ~/Downloads/student-recoding_8kzmRlv.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_QuzFCTY.mp3 ~/Downloads/student-recoding_QuzFCTY.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_ZSpsdOv.mp3 ~/Downloads/student-recoding_ZSpsdOv.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_f1XXQvN.mp3 ~/Downloads/student-recoding_f1XXQvN.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_zrdrZ9V.mp3 ~/Downloads/student-recoding_zrdrZ9V.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_4LAceJ0.mp3 ~/Downloads/student-recoding_4LAceJ0.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_rq4Ed4z.mp3 ~/Downloads/student-recoding_rq4Ed4z.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_4mAu4tA.mp3 ~/Downloads/student-recoding_4mAu4tA.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_4qyooKJ.mp3 ~/Downloads/student-recoding_4qyooKJ.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_x47Vo0c.mp3 ~/Downloads/student-recoding_x47Vo0c.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_5EXnBJa.mp3 ~/Downloads/student-recoding_5EXnBJa.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_g1e0I4P.mp3 ~/Downloads/student-recoding_g1e0I4P.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_1h9yKm3.mp3 ~/Downloads/student-recoding_1h9yKm3.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_lDZCgMV.mp3 ~/Downloads/student-recoding_lDZCgMV.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_5i22Rg9.mp3 ~/Downloads/student-recoding_5i22Rg9.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_meSaxcp.mp3 ~/Downloads/student-recoding_meSaxcp.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_ntCi9FU.mp3 ~/Downloads/student-recoding_ntCi9FU.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_3KMfLfZ.mp3 ~/Downloads/student-recoding_3KMfLfZ.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_AiwNiu3.mp3 ~/Downloads/student-recoding_AiwNiu3.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_q7D73kW.mp3 ~/Downloads/student-recoding_q7D73kW.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_QPe39SB.mp3 ~/Downloads/student-recoding_QPe39SB.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_b4kxgTz.mp3 ~/Downloads/student-recoding_b4kxgTz.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_7tqpFAJ.mp3 ~/Downloads/student-recoding_7tqpFAJ.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_GbZ8U8d.mp3 ~/Downloads/student-recoding_GbZ8U8d.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_GHcvPQK.mp3 ~/Downloads/student-recoding_GHcvPQK.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_aiPaPKV.mp3 ~/Downloads/student-recoding_aiPaPKV.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_ig1u2fA.mp3 ~/Downloads/student-recoding_ig1u2fA.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_ZQxYZDe.mp3 ~/Downloads/student-recoding_ZQxYZDe.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_lrGZoAR.mp3 ~/Downloads/student-recoding_lrGZoAR.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_jlAq6D1.mp3 ~/Downloads/student-recoding_jlAq6D1.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_iNhpZVt.mp3 ~/Downloads/student-recoding_iNhpZVt.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_g8LwlBM.mp3 ~/Downloads/student-recoding_g8LwlBM.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_Wmd2cfq.mp3 ~/Downloads/student-recoding_Wmd2cfq.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_lrOQ2cb.mp3 ~/Downloads/student-recoding_lrOQ2cb.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_zS5A2yj.mp3 ~/Downloads/student-recoding_zS5A2yj.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_sIRntXr.mp3 ~/Downloads/student-recoding_sIRntXr.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_d5JHLY5.mp3 ~/Downloads/student-recoding_d5JHLY5.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_67Xa737.mp3 ~/Downloads/student-recoding_67Xa737.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_tfCCggl.mp3 ~/Downloads/student-recoding_tfCCggl.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_sjsiRpv.mp3 ~/Downloads/student-recoding_sjsiRpv.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_1jNacmn.mp3 ~/Downloads/student-recoding_1jNacmn.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_0N89hwo.mp3 ~/Downloads/student-recoding_0N89hwo.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_8e2Ecvb.mp3 ~/Downloads/student-recoding_8e2Ecvb.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_OP0sLVG.mp3 ~/Downloads/student-recoding_OP0sLVG.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_gZzQ6Hs.mp3 ~/Downloads/student-recoding_gZzQ6Hs.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_VlUTCih.mp3 ~/Downloads/student-recoding_VlUTCih.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_vT44ic0.mp3 ~/Downloads/student-recoding_vT44ic0.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_Rbd6YyS.mp3 ~/Downloads/student-recoding_Rbd6YyS.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_eZA8pg7.mp3 ~/Downloads/student-recoding_eZA8pg7.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_2NI98S3.mp3 ~/Downloads/student-recoding_2NI98S3.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_URmKReI.mp3 ~/Downloads/student-recoding_URmKReI.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_8LjMG2n.mp3 ~/Downloads/student-recoding_8LjMG2n.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_1XSu26R.mp3 ~/Downloads/student-recoding_1XSu26R.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_63gLiPw.mp3 ~/Downloads/student-recoding_63gLiPw.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_W3WAeRd.mp3 ~/Downloads/student-recoding_W3WAeRd.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_0T2wAVK.mp3 ~/Downloads/student-recoding_0T2wAVK.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_WTjZnuS.mp3 ~/Downloads/student-recoding_WTjZnuS.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_KiFfNUT.mp3 ~/Downloads/student-recoding_KiFfNUT.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_5Q8ZqIi.mp3 ~/Downloads/student-recoding_5Q8ZqIi.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_6bEB7Mf.mp3 ~/Downloads/student-recoding_6bEB7Mf.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_YRxJLfV.mp3 ~/Downloads/student-recoding_YRxJLfV.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_BI0ww0u.mp3 ~/Downloads/student-recoding_BI0ww0u.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_qrPPh93.mp3 ~/Downloads/student-recoding_qrPPh93.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_UYX4DVU.mp3 ~/Downloads/student-recoding_UYX4DVU.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_kQvJDuY.mp3 ~/Downloads/student-recoding_kQvJDuY.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_sfe8vib.mp3 ~/Downloads/student-recoding_sfe8vib.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_0KJabag.mp3 ~/Downloads/student-recoding_0KJabag.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_DNdBQQp.mp3 ~/Downloads/student-recoding_DNdBQQp.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_tUyX2ta.mp3 ~/Downloads/student-recoding_tUyX2ta.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_f0Jub5t.mp3 ~/Downloads/student-recoding_f0Jub5t.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_5pr3RA6.mp3 ~/Downloads/student-recoding_5pr3RA6.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_9NHAEWc.mp3 ~/Downloads/student-recoding_9NHAEWc.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_SdfrFBS.mp3 ~/Downloads/student-recoding_SdfrFBS.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_O4RbmJI.mp3 ~/Downloads/student-recoding_O4RbmJI.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_LrBm0Le.mp3 ~/Downloads/student-recoding_LrBm0Le.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_1uddeZF.mp3 ~/Downloads/student-recoding_1uddeZF.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_ZfUS5h3.mp3 ~/Downloads/student-recoding_ZfUS5h3.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_h4H9CVP.mp3 ~/Downloads/student-recoding_h4H9CVP.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_beMcrJm.mp3 ~/Downloads/student-recoding_beMcrJm.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_py3eSsR.mp3 ~/Downloads/student-recoding_py3eSsR.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_hEtE6bi.mp3 ~/Downloads/student-recoding_hEtE6bi.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_MvYBgPj.mp3 ~/Downloads/student-recoding_MvYBgPj.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_87cXcWN.mp3 ~/Downloads/student-recoding_87cXcWN.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_HyctO2g.mp3 ~/Downloads/student-recoding_HyctO2g.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_kJdlKP4.mp3 ~/Downloads/student-recoding_kJdlKP4.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_LOVxw2H.mp3 ~/Downloads/student-recoding_LOVxw2H.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_q2DFdyD.mp3 ~/Downloads/student-recoding_q2DFdyD.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_nu3JDUz.mp3 ~/Downloads/student-recoding_nu3JDUz.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_kSBWFA2.mp3 ~/Downloads/student-recoding_kSBWFA2.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_ogbDA8X.mp3 ~/Downloads/student-recoding_ogbDA8X.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_PMyVTBb.mp3 ~/Downloads/student-recoding_PMyVTBb.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_OU3YKjF.mp3 ~/Downloads/student-recoding_OU3YKjF.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_2CIr77U.mp3 ~/Downloads/student-recoding_2CIr77U.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_PSmcvDq.mp3 ~/Downloads/student-recoding_PSmcvDq.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_yU3aIrS.mp3 ~/Downloads/student-recoding_yU3aIrS.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_Ot2RQih.mp3 ~/Downloads/student-recoding_Ot2RQih.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_QYtNE1F.mp3 ~/Downloads/student-recoding_QYtNE1F.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_7ZNGYFl.mp3 ~/Downloads/student-recoding_7ZNGYFl.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_70djkh9.mp3 ~/Downloads/student-recoding_70djkh9.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_Vb4OzZl.mp3 ~/Downloads/student-recoding_Vb4OzZl.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_tBzNjg0.mp3 ~/Downloads/student-recoding_tBzNjg0.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_5khMkmS.mp3 ~/Downloads/student-recoding_5khMkmS.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_7DXkGZd.mp3 ~/Downloads/student-recoding_7DXkGZd.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_PU7ZF1C.mp3 ~/Downloads/student-recoding_PU7ZF1C.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_089bMXx.mp3 ~/Downloads/student-recoding_089bMXx.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_9HdrhrI.mp3 ~/Downloads/student-recoding_9HdrhrI.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_VCQLR9I.mp3 ~/Downloads/student-recoding_VCQLR9I.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_FhtEO84.mp3 ~/Downloads/student-recoding_FhtEO84.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_Qa4iBlm.mp3 ~/Downloads/student-recoding_Qa4iBlm.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_0f0EoY2.mp3 ~/Downloads/student-recoding_0f0EoY2.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_UGX8dST.mp3 ~/Downloads/student-recoding_UGX8dST.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_AZtIYcr.mp3 ~/Downloads/student-recoding_AZtIYcr.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_1eF5f48.mp3 ~/Downloads/student-recoding_1eF5f48.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_HJlkWxa.mp3 ~/Downloads/student-recoding_HJlkWxa.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_Hf3BfZ5.mp3 ~/Downloads/student-recoding_Hf3BfZ5.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_9MoMNws.mp3 ~/Downloads/student-recoding_9MoMNws.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_dGxDly0.mp3 ~/Downloads/student-recoding_dGxDly0.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_1qZvgDh.mp3 ~/Downloads/student-recoding_1qZvgDh.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_uZx0jHN.mp3 ~/Downloads/student-recoding_uZx0jHN.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_no8giT7.mp3 ~/Downloads/student-recoding_no8giT7.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_1mwNhV4.mp3 ~/Downloads/student-recoding_1mwNhV4.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_93ojXag.mp3 ~/Downloads/student-recoding_93ojXag.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_XVsPSSK.mp3 ~/Downloads/student-recoding_XVsPSSK.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_mGCKtdY.mp3 ~/Downloads/student-recoding_mGCKtdY.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_Cl7O9OW.mp3 ~/Downloads/student-recoding_Cl7O9OW.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_6UrbBQj.mp3 ~/Downloads/student-recoding_6UrbBQj.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_D5gOMVM.mp3 ~/Downloads/student-recoding_D5gOMVM.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_26BIF0h.mp3 ~/Downloads/student-recoding_26BIF0h.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_vvHVCCc.mp3 ~/Downloads/student-recoding_vvHVCCc.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_9DzHQg7.mp3 ~/Downloads/student-recoding_9DzHQg7.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_B2iBnaM.mp3 ~/Downloads/student-recoding_B2iBnaM.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_wODPfYZ.mp3 ~/Downloads/student-recoding_wODPfYZ.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_EcM9Uop.mp3 ~/Downloads/student-recoding_EcM9Uop.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_qoOW9WH.mp3 ~/Downloads/student-recoding_qoOW9WH.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_0ge6z6R.mp3 ~/Downloads/student-recoding_0ge6z6R.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_yo6iFy2.mp3 ~/Downloads/student-recoding_yo6iFy2.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_FjAk2G5.mp3 ~/Downloads/student-recoding_FjAk2G5.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_RET7Rxc.mp3 ~/Downloads/student-recoding_RET7Rxc.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_o6iGiC4.mp3 ~/Downloads/student-recoding_o6iGiC4.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_ILfJJ4m.mp3 ~/Downloads/student-recoding_ILfJJ4m.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_vddxWGc.mp3 ~/Downloads/student-recoding_vddxWGc.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_a2IeMXA.mp3 ~/Downloads/student-recoding_a2IeMXA.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_eBihmLt.mp3 ~/Downloads/student-recoding_eBihmLt.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_gbZtKVD.mp3 ~/Downloads/student-recoding_gbZtKVD.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_lpA6LMK.mp3 ~/Downloads/student-recoding_lpA6LMK.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_tyfzWkN.mp3 ~/Downloads/student-recoding_tyfzWkN.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_SHB8iAi.mp3 ~/Downloads/student-recoding_SHB8iAi.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_FeCZmWf.mp3 ~/Downloads/student-recoding_FeCZmWf.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_X3T0nIk.mp3 ~/Downloads/student-recoding_X3T0nIk.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_fSIg5zA.mp3 ~/Downloads/student-recoding_fSIg5zA.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_K3IwJIk.mp3 ~/Downloads/student-recoding_K3IwJIk.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_EnRQkLP.mp3 ~/Downloads/student-recoding_EnRQkLP.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_BydEMbJ.mp3 ~/Downloads/student-recoding_BydEMbJ.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_kWzKpBl.mp3 ~/Downloads/student-recoding_kWzKpBl.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_BfWB6mB.mp3 ~/Downloads/student-recoding_BfWB6mB.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_TvfrNwR.mp3 ~/Downloads/student-recoding_TvfrNwR.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_t7GIZ0P.mp3 ~/Downloads/student-recoding_t7GIZ0P.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_pPOh9Ex.mp3 ~/Downloads/student-recoding_pPOh9Ex.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_vOkFlXA.mp3 ~/Downloads/student-recoding_vOkFlXA.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_vgCUo3Q.mp3 ~/Downloads/student-recoding_vgCUo3Q.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_KUfHpH1.mp3 ~/Downloads/student-recoding_KUfHpH1.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_R3dYU5S.mp3 ~/Downloads/student-recoding_R3dYU5S.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_n2gNygK.mp3 ~/Downloads/student-recoding_n2gNygK.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_rfBsHnm.mp3 ~/Downloads/student-recoding_rfBsHnm.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_60Mu47C.mp3 ~/Downloads/student-recoding_60Mu47C.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_VmtZZkJ.mp3 ~/Downloads/student-recoding_VmtZZkJ.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_hKqoTQd.mp3 ~/Downloads/student-recoding_hKqoTQd.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_qFsfJOR.mp3 ~/Downloads/student-recoding_qFsfJOR.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_D8sCnit.mp3 ~/Downloads/student-recoding_D8sCnit.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_AKnzpYs.mp3 ~/Downloads/student-recoding_AKnzpYs.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_V0dCD8e.mp3 ~/Downloads/student-recoding_V0dCD8e.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_KDv1e0K.mp3 ~/Downloads/student-recoding_KDv1e0K.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_gKU8U7J.mp3 ~/Downloads/student-recoding_gKU8U7J.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_RN5Rbkq.mp3 ~/Downloads/student-recoding_RN5Rbkq.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_Tbgob2j.mp3 ~/Downloads/student-recoding_Tbgob2j.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_ytSQixG.mp3 ~/Downloads/student-recoding_ytSQixG.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_quepY3W.mp3 ~/Downloads/student-recoding_quepY3W.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_IvPwVMD.mp3 ~/Downloads/student-recoding_IvPwVMD.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_HgibjIZ.mp3 ~/Downloads/student-recoding_HgibjIZ.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_w473wIU.mp3 ~/Downloads/student-recoding_w473wIU.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_q1Nlyvl.mp3 ~/Downloads/student-recoding_q1Nlyvl.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_fhkF6jd.mp3 ~/Downloads/student-recoding_fhkF6jd.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_0RkWk5v.mp3 ~/Downloads/student-recoding_0RkWk5v.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_JeLdkFz.mp3 ~/Downloads/student-recoding_JeLdkFz.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_2NAHwb5.mp3 ~/Downloads/student-recoding_2NAHwb5.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_dW62Tq4.mp3 ~/Downloads/student-recoding_dW62Tq4.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_CpfPgOU.mp3 ~/Downloads/student-recoding_CpfPgOU.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_GQTJU9E.mp3 ~/Downloads/student-recoding_GQTJU9E.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_8GyNdYN.mp3 ~/Downloads/student-recoding_8GyNdYN.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_CwKKPUG.mp3 ~/Downloads/student-recoding_CwKKPUG.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_TNlt17J.mp3 ~/Downloads/student-recoding_TNlt17J.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_UDuhGf8.mp3 ~/Downloads/student-recoding_UDuhGf8.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_iZgoguV.mp3 ~/Downloads/student-recoding_iZgoguV.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_KsWuXTy.mp3 ~/Downloads/student-recoding_KsWuXTy.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_58oCfns.mp3 ~/Downloads/student-recoding_58oCfns.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_BDQ8Kcx.mp3 ~/Downloads/student-recoding_BDQ8Kcx.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_qAEO1y1.mp3 ~/Downloads/student-recoding_qAEO1y1.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_6BzLGGJ.mp3 ~/Downloads/student-recoding_6BzLGGJ.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_zxCSpaY.mp3 ~/Downloads/student-recoding_zxCSpaY.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_0CA7NvJ.mp3 ~/Downloads/student-recoding_0CA7NvJ.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_CTvAlSm.mp3 ~/Downloads/student-recoding_CTvAlSm.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_pwav2tH.mp3 ~/Downloads/student-recoding_pwav2tH.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_RZNHqvm.mp3 ~/Downloads/student-recoding_RZNHqvm.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_QeUGb6D.mp3 ~/Downloads/student-recoding_QeUGb6D.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_EQeErn5.mp3 ~/Downloads/student-recoding_EQeErn5.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_TjD1Yxz.mp3 ~/Downloads/student-recoding_TjD1Yxz.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_nQ21lG0.mp3 ~/Downloads/student-recoding_nQ21lG0.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_Wrv5Jr8.mp3 ~/Downloads/student-recoding_Wrv5Jr8.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_E0xjWEs.mp3 ~/Downloads/student-recoding_E0xjWEs.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_kKNjwy0.mp3 ~/Downloads/student-recoding_kKNjwy0.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_U1qysrf.mp3 ~/Downloads/student-recoding_U1qysrf.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_poZySOm.mp3 ~/Downloads/student-recoding_poZySOm.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_gZOIlCc.mp3 ~/Downloads/student-recoding_gZOIlCc.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_a3sSOiz.mp3 ~/Downloads/student-recoding_a3sSOiz.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_YFyany6.mp3 ~/Downloads/student-recoding_YFyany6.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_a136s08.mp3 ~/Downloads/student-recoding_a136s08.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_c4oJ2B3.mp3 ~/Downloads/student-recoding_c4oJ2B3.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_xau7cin.mp3 ~/Downloads/student-recoding_xau7cin.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_DDXCiqT.mp3 ~/Downloads/student-recoding_DDXCiqT.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_m5xAmMq.mp3 ~/Downloads/student-recoding_m5xAmMq.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_pTPbmRL.mp3 ~/Downloads/student-recoding_pTPbmRL.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_HndNzR8.mp3 ~/Downloads/student-recoding_HndNzR8.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_UELlRTs.mp3 ~/Downloads/student-recoding_UELlRTs.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_dPcvDXB.mp3 ~/Downloads/student-recoding_dPcvDXB.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_WGeuOua.mp3 ~/Downloads/student-recoding_WGeuOua.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_V1pgnC8.mp3 ~/Downloads/student-recoding_V1pgnC8.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_Ul6dqw7.mp3 ~/Downloads/student-recoding_Ul6dqw7.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_fY94tC7.mp3 ~/Downloads/student-recoding_fY94tC7.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_Q01D4yh.mp3 ~/Downloads/student-recoding_Q01D4yh.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_irPOZAb.mp3 ~/Downloads/student-recoding_irPOZAb.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_ohSdfhB.mp3 ~/Downloads/student-recoding_ohSdfhB.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_53XSzDi.mp3 ~/Downloads/student-recoding_53XSzDi.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_4mpSiKk.mp3 ~/Downloads/student-recoding_4mpSiKk.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_rWw0QlW.mp3 ~/Downloads/student-recoding_rWw0QlW.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_LajEAG5.mp3 ~/Downloads/student-recoding_LajEAG5.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_s6nYuHz.mp3 ~/Downloads/student-recoding_s6nYuHz.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_Ce3cwlO.mp3 ~/Downloads/student-recoding_Ce3cwlO.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_uK27rhX.mp3 ~/Downloads/student-recoding_uK27rhX.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_aLNRyGD.mp3 ~/Downloads/student-recoding_aLNRyGD.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_ExCvq4C.mp3 ~/Downloads/student-recoding_ExCvq4C.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_788cRiU.mp3 ~/Downloads/student-recoding_788cRiU.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_Pg5xpdq.mp3 ~/Downloads/student-recoding_Pg5xpdq.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_DlfAd5e.mp3 ~/Downloads/student-recoding_DlfAd5e.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_JKe3vDO.mp3 ~/Downloads/student-recoding_JKe3vDO.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_kaMWEpB.mp3 ~/Downloads/student-recoding_kaMWEpB.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_dzF09LG.mp3 ~/Downloads/student-recoding_dzF09LG.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_vTmDKBR.mp3 ~/Downloads/student-recoding_vTmDKBR.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_KBn2btU.mp3 ~/Downloads/student-recoding_KBn2btU.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_2ZeAu7A.mp3 ~/Downloads/student-recoding_2ZeAu7A.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_9dtHrDQ.mp3 ~/Downloads/student-recoding_9dtHrDQ.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_wMEVifG.mp3 ~/Downloads/student-recoding_wMEVifG.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_2VSsaYn.mp3 ~/Downloads/student-recoding_2VSsaYn.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_NVz9VD3.mp3 ~/Downloads/student-recoding_NVz9VD3.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_dEydYZp.mp3 ~/Downloads/student-recoding_dEydYZp.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_KTzx1tD.mp3 ~/Downloads/student-recoding_KTzx1tD.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_AQK3nA5.mp3 ~/Downloads/student-recoding_AQK3nA5.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_kCM4ESf.mp3 ~/Downloads/student-recoding_kCM4ESf.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_FrWCYMR.mp3 ~/Downloads/student-recoding_FrWCYMR.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_SWVBaS1.mp3 ~/Downloads/student-recoding_SWVBaS1.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_ICc8onS.mp3 ~/Downloads/student-recoding_ICc8onS.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_MtdsLgE.mp3 ~/Downloads/student-recoding_MtdsLgE.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_3WhpjMh.mp3 ~/Downloads/student-recoding_3WhpjMh.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_1vXTCVP.mp3 ~/Downloads/student-recoding_1vXTCVP.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_SscRfN9.mp3 ~/Downloads/student-recoding_SscRfN9.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_UXtlceZ.mp3 ~/Downloads/student-recoding_UXtlceZ.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_3dkMCbc.mp3 ~/Downloads/student-recoding_3dkMCbc.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_vBlq9OP.mp3 ~/Downloads/student-recoding_vBlq9OP.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_Q9mr3UD.mp3 ~/Downloads/student-recoding_Q9mr3UD.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_uZJyd2q.mp3 ~/Downloads/student-recoding_uZJyd2q.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_EE1ZtlM.mp3 ~/Downloads/student-recoding_EE1ZtlM.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_Uv3ZxNI.mp3 ~/Downloads/student-recoding_Uv3ZxNI.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_z8oOlF4.mp3 ~/Downloads/student-recoding_z8oOlF4.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_E3ySeFX.mp3 ~/Downloads/student-recoding_E3ySeFX.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_DvlgTbG.mp3 ~/Downloads/student-recoding_DvlgTbG.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_zwSfg84.mp3 ~/Downloads/student-recoding_zwSfg84.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_uWHcE4s.mp3 ~/Downloads/student-recoding_uWHcE4s.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_Mac3gji.mp3 ~/Downloads/student-recoding_Mac3gji.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_NfVrW2H.mp3 ~/Downloads/student-recoding_NfVrW2H.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_abPjq2w.mp3 ~/Downloads/student-recoding_abPjq2w.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_q7bKQlL.mp3 ~/Downloads/student-recoding_q7bKQlL.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_H22pxxQ.mp3 ~/Downloads/student-recoding_H22pxxQ.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_Fh4Om6Z.mp3 ~/Downloads/student-recoding_Fh4Om6Z.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_9fLVFvx.mp3 ~/Downloads/student-recoding_9fLVFvx.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_01B0rat.mp3 ~/Downloads/student-recoding_01B0rat.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_Y9t3Q0I.mp3 ~/Downloads/student-recoding_Y9t3Q0I.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_3oJv5oR.mp3 ~/Downloads/student-recoding_3oJv5oR.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_PadYlYv.mp3 ~/Downloads/student-recoding_PadYlYv.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_JKQrrpi.mp3 ~/Downloads/student-recoding_JKQrrpi.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_X66j8cE.mp3 ~/Downloads/student-recoding_X66j8cE.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_HFjBHLH.mp3 ~/Downloads/student-recoding_HFjBHLH.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_a3PlE3m.mp3 ~/Downloads/student-recoding_a3PlE3m.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_9W5vJk7.mp3 ~/Downloads/student-recoding_9W5vJk7.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_g9rkd86.mp3 ~/Downloads/student-recoding_g9rkd86.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_coKprRH.mp3 ~/Downloads/student-recoding_coKprRH.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_2hcZh0p.mp3 ~/Downloads/student-recoding_2hcZh0p.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_vM6NsKj.mp3 ~/Downloads/student-recoding_vM6NsKj.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_UDL9AFg.mp3 ~/Downloads/student-recoding_UDL9AFg.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_bF5q5kq.mp3 ~/Downloads/student-recoding_bF5q5kq.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_I9IBGuU.mp3 ~/Downloads/student-recoding_I9IBGuU.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_KJEvQpG.mp3 ~/Downloads/student-recoding_KJEvQpG.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_f7Ttc29.mp3 ~/Downloads/student-recoding_f7Ttc29.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_8gqTpAF.mp3 ~/Downloads/student-recoding_8gqTpAF.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_yQwM60W.mp3 ~/Downloads/student-recoding_yQwM60W.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_vzHp1Bx.mp3 ~/Downloads/student-recoding_vzHp1Bx.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_a95LhlN.mp3 ~/Downloads/student-recoding_a95LhlN.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_T0VwsI4.mp3 ~/Downloads/student-recoding_T0VwsI4.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_d0ICqx6.mp3 ~/Downloads/student-recoding_d0ICqx6.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_lk6cTfz.mp3 ~/Downloads/student-recoding_lk6cTfz.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_hf57sqv.mp3 ~/Downloads/student-recoding_hf57sqv.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_4EcTasa.mp3 ~/Downloads/student-recoding_4EcTasa.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_Zx0ACbj.mp3 ~/Downloads/student-recoding_Zx0ACbj.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_pCZh1vJ.mp3 ~/Downloads/student-recoding_pCZh1vJ.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_irE2bar.mp3 ~/Downloads/student-recoding_irE2bar.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_eEC6zuK.mp3 ~/Downloads/student-recoding_eEC6zuK.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_BqGrYAm.mp3 ~/Downloads/student-recoding_BqGrYAm.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_rl3qmpt.mp3 ~/Downloads/student-recoding_rl3qmpt.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_Fz99q0Y.mp3 ~/Downloads/student-recoding_Fz99q0Y.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_V4HUZ1d.mp3 ~/Downloads/student-recoding_V4HUZ1d.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_APgM42M.mp3 ~/Downloads/student-recoding_APgM42M.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_minqdP2.mp3 ~/Downloads/student-recoding_minqdP2.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_HrwXi8F.mp3 ~/Downloads/student-recoding_HrwXi8F.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_l0kHWmg.mp3 ~/Downloads/student-recoding_l0kHWmg.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_713h2EN.mp3 ~/Downloads/student-recoding_713h2EN.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_Z7XDgRF.mp3 ~/Downloads/student-recoding_Z7XDgRF.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_m7f5T9b.mp3 ~/Downloads/student-recoding_m7f5T9b.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_hT2kRT1.mp3 ~/Downloads/student-recoding_hT2kRT1.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_Wli0U2f.mp3 ~/Downloads/student-recoding_Wli0U2f.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_YoU6R2X.mp3 ~/Downloads/student-recoding_YoU6R2X.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_qk3pfZp.mp3 ~/Downloads/student-recoding_qk3pfZp.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_mUyuW71.mp3 ~/Downloads/student-recoding_mUyuW71.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_QG8MDhH.mp3 ~/Downloads/student-recoding_QG8MDhH.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_xExjXsG.mp3 ~/Downloads/student-recoding_xExjXsG.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_WOp1AXU.mp3 ~/Downloads/student-recoding_WOp1AXU.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_69mqarK.mp3 ~/Downloads/student-recoding_69mqarK.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_FhMbuFp.mp3 ~/Downloads/student-recoding_FhMbuFp.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_5oSc6sP.mp3 ~/Downloads/student-recoding_5oSc6sP.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_woM3EKE.mp3 ~/Downloads/student-recoding_woM3EKE.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_Q68FwdB.mp3 ~/Downloads/student-recoding_Q68FwdB.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_clckAJz.mp3 ~/Downloads/student-recoding_clckAJz.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_mxZdfvS.mp3 ~/Downloads/student-recoding_mxZdfvS.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_61INJdi.mp3 ~/Downloads/student-recoding_61INJdi.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_Uhb4n5W.mp3 ~/Downloads/student-recoding_Uhb4n5W.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_azisqUR.mp3 ~/Downloads/student-recoding_azisqUR.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_H9nxQIj.mp3 ~/Downloads/student-recoding_H9nxQIj.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_qe7TXo1.mp3 ~/Downloads/student-recoding_qe7TXo1.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_B8hy0OV.mp3 ~/Downloads/student-recoding_B8hy0OV.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_c5Wz4fi.mp3 ~/Downloads/student-recoding_c5Wz4fi.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_TyY0KJy.mp3 ~/Downloads/student-recoding_TyY0KJy.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_HEJXMxi.mp3 ~/Downloads/student-recoding_HEJXMxi.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_aMyPS6p.mp3 ~/Downloads/student-recoding_aMyPS6p.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_rB4iZmo.mp3 ~/Downloads/student-recoding_rB4iZmo.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_w8Vnm6O.mp3 ~/Downloads/student-recoding_w8Vnm6O.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_bUOWBCr.mp3 ~/Downloads/student-recoding_bUOWBCr.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_1SV9Gyl.mp3 ~/Downloads/student-recoding_1SV9Gyl.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_wgItPfW.mp3 ~/Downloads/student-recoding_wgItPfW.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_AX2qlrP.mp3 ~/Downloads/student-recoding_AX2qlrP.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_i5LN44D.mp3 ~/Downloads/student-recoding_i5LN44D.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_STa1TfL.mp3 ~/Downloads/student-recoding_STa1TfL.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_S3N3XX2.mp3 ~/Downloads/student-recoding_S3N3XX2.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_zPt3VCd.mp3 ~/Downloads/student-recoding_zPt3VCd.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_VP8O7L2.mp3 ~/Downloads/student-recoding_VP8O7L2.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_y5aHCM0.mp3 ~/Downloads/student-recoding_y5aHCM0.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_6ZFNyWP.mp3 ~/Downloads/student-recoding_6ZFNyWP.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_fin2jOc.mp3 ~/Downloads/student-recoding_fin2jOc.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_bDw1Ieu.mp3 ~/Downloads/student-recoding_bDw1Ieu.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_NGfHyE0.mp3 ~/Downloads/student-recoding_NGfHyE0.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_MWMonCB.mp3 ~/Downloads/student-recoding_MWMonCB.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_fUodLW1.mp3 ~/Downloads/student-recoding_fUodLW1.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_FIvY7ek.mp3 ~/Downloads/student-recoding_FIvY7ek.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_QTy0XK6.mp3 ~/Downloads/student-recoding_QTy0XK6.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_CsKRC3d.mp3 ~/Downloads/student-recoding_CsKRC3d.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_zBn16gb.mp3 ~/Downloads/student-recoding_zBn16gb.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_aKUZzgV.mp3 ~/Downloads/student-recoding_aKUZzgV.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_Nn0E4GM.mp3 ~/Downloads/student-recoding_Nn0E4GM.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_RgXw8V3.mp3 ~/Downloads/student-recoding_RgXw8V3.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_3JX9zVR.mp3 ~/Downloads/student-recoding_3JX9zVR.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_85OhYrk.mp3 ~/Downloads/student-recoding_85OhYrk.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_wW5Tlr4.mp3 ~/Downloads/student-recoding_wW5Tlr4.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_RKdCxIR.mp3 ~/Downloads/student-recoding_RKdCxIR.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_KRaa5RI.mp3 ~/Downloads/student-recoding_KRaa5RI.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_BwxcGFA.mp3 ~/Downloads/student-recoding_BwxcGFA.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_Yv77pkT.mp3 ~/Downloads/student-recoding_Yv77pkT.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_EMZtbyE.mp3 ~/Downloads/student-recoding_EMZtbyE.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_MKTEWDr.mp3 ~/Downloads/student-recoding_MKTEWDr.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_vJM5vvd.mp3 ~/Downloads/student-recoding_vJM5vvd.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_Jj7EXMZ.mp3 ~/Downloads/student-recoding_Jj7EXMZ.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_anmRal0.mp3 ~/Downloads/student-recoding_anmRal0.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_xP9St0V.mp3 ~/Downloads/student-recoding_xP9St0V.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_kY7Z2IW.mp3 ~/Downloads/student-recoding_kY7Z2IW.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_oD05qjx.mp3 ~/Downloads/student-recoding_oD05qjx.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_FPKqu8f.mp3 ~/Downloads/student-recoding_FPKqu8f.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_44rgV3m.mp3 ~/Downloads/student-recoding_44rgV3m.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_V4FXfTr.mp3 ~/Downloads/student-recoding_V4FXfTr.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_wUy1BL6.mp3 ~/Downloads/student-recoding_wUy1BL6.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_jgPyGhd.mp3 ~/Downloads/student-recoding_jgPyGhd.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_erzzTdH.mp3 ~/Downloads/student-recoding_erzzTdH.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_Uez7rCa.mp3 ~/Downloads/student-recoding_Uez7rCa.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_KCDidv9.mp3 ~/Downloads/student-recoding_KCDidv9.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_eDjVvuf.mp3 ~/Downloads/student-recoding_eDjVvuf.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_9ZqYXE4.mp3 ~/Downloads/student-recoding_9ZqYXE4.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_ZXNZAmu.mp3 ~/Downloads/student-recoding_ZXNZAmu.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_4sZfsww.mp3 ~/Downloads/student-recoding_4sZfsww.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_ay0Bp4x.mp3 ~/Downloads/student-recoding_ay0Bp4x.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_Mlc8XFL.mp3 ~/Downloads/student-recoding_Mlc8XFL.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_67loKRY.mp3 ~/Downloads/student-recoding_67loKRY.mp3 --no-cli-pager
aws --profile cprprod s3api get-object --bucket "api-musiccpr-prod" --key media/student-recoding_HS7nK7l.mp3 ~/Downloads/student-recoding_HS7nK7l.mp3 --no-cli-pager